(venv) axels-mbp:python axel.eriksson$ python main.py
Python Client runs using RSA authentication
Starting datafeed
Traceback (most recent call last):
  File "main.py", line 67, in <module>
    main()
  File "main.py", line 59, in main
    loop.run_until_complete(datafeed_event_service.start_datafeed())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/axel.eriksson/symphony-bots/fx-bot/venv/lib/python3.7/site-packages/sym_api_client_python/datafeed_event_service.py", line 401, in start_datafeed
    self.datafeed_id = self.datafeed_client.create_datafeed()
  File "/Users/axel.eriksson/symphony-bots/fx-bot/venv/lib/python3.7/site-packages/sym_api_client_python/clients/datafeed_client.py", line 29, in create_datafeed
    response = self.bot_client.execute_rest_call("POST", url)
  File "/Users/axel.eriksson/symphony-bots/fx-bot/venv/lib/python3.7/site-packages/sym_api_client_python/clients/sym_bot_client.py", line 188, in execute_rest_call
    super().handle_error(response, self, error_json, text)
  File "/Users/axel.eriksson/symphony-bots/fx-bot/venv/lib/python3.7/site-packages/sym_api_client_python/clients/api_client.py", line 113, in handle_error
    .format(err_message, response.__dict__))
sym_api_client_python.exceptions.APIClientErrorException.APIClientErrorException: Client Error Occurred: <html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
. Response contents: {'_content': b'<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n', '_content_consumed': True, '_next': None, 'status_code': 404, 'headers': {'Content-Type': 'text/html', 'Date': 'Sat, 16 May 2020 22:51:40 GMT', 'Server': 'nginx', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Length': '146', 'Connection': 'keep-alive'}, 'raw': <urllib3.response.HTTPResponse object at 0x10438f4a8>, 'url': 'https://rtc1.symphony.com:443/agent/v4/datafeed/create', 'encoding': 'ISO-8859-1', 'history': [], 'reason': 'Not Found', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=647685), 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x10438fa58>}